1.import cv2
import matplotlib.pyplot as plt
image=cv2.imread("happy_dog.jpg")
color=cv2.imread("istockphoto-1140180560-612x612.jpg".)
hist=cv2.calcHist([image],[0],None,[256],[0,256])
hist1=cv2.calcHist([color],[1],None,[256],[0,256])
plt.imshow(image)
plt.show()
plt.imshow(color)
plt.show()
plt.figure()
plt.title("Histogram")
plt.xlabel("gvalue")
plt.ylabel("pixel")
plt.stem(hist)
plt.show()
plt.stem(hist1)
plt.show()
2.import cv2
import matplotlib.pyplot as plt
image=cv2.imread("happy_dog.jpg",0)
equ=cv2.equalizeHist(image)
equ1=cv2.resize(equ, (780, 540),interpolation = cv2.INTER_NEAREST)
egray=cv2.imshow("equ",equ1)
hist=cv2.calcHist([equ1],[0],None,[256],[0,256])
plt.stem(hist)
plt.show()
cv2.waitKey(0)
cv2.destroyAllWindows()